namespace: rtpengine
namespaceCreate: true

statefulset:
  name: rtpengine
  replicas: 1

service:
  headless:
    name: rtpengine

image:
  repository: bundasmanu/rtpengine-docker
  tag: latest
  pullPolicy: Always

rtpengine:
  user: rtpengine
  confDir: /etc/rtpengine/conf
  logDir: /etc/rtpengine/logs
  recordingsDir: /etc/rtpengine/recordings
  logFilename: rtpengine
  listen:
    externalIP: "127.0.0.1"
    ngPort: 2223
    cliPort: 2224
    httpPort: 2226
  defaultInterface:
    minPort: 10000
    maxPort: 20000

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

persistence:
  enabled: true
  storageClass: local-path
  size: 10Gi
  accessMode: ReadWriteOnce
