pods:
  - name: rtpengine-a
    listenIP: "127.0.0.1"
    ports:
      ng: 2223
      cli: 2224
      rtp: 22222
  - name: rtpengine-b
    listenIP: "172.27.27.27"
    ports:
      ng: 2323
      cli: 2324
      rtp: 23222

image:
  repository: bundasmanu/rtpengine
  tag: 1.0.0
  pullPolicy: Always

rtpengine:
  user: rtpengine
  confDir: /etc/rtpengine
  logDir: /etc/rtpengine/logs
  recordingsDir: /etc/rtpengine/recordings
  logFilename: rtpengine
  defaultInterface:
    minPort: 10000
    maxPort: 20000

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

persistence:
  enabled: true
  storageClass: local-path
  size: 10Gi
  accessMode: ReadWriteOnce
